AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - db/schema.rb
    - spec/dummy/db/schema.rb

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLines:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 250

# .find_each is not the same as .each
Rails/FindEach:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Will report offences for many places that are much more readable without using a guard clause
Style/GuardClause:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/SymbolArray:
  Enabled: false

Style/TrivialAccessors:
  ExactNameMatch: true
  Enabled: true
