AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - db/schema.rb
    - spec/dummy/db/schema.rb

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/EmptyLines:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Max: 160

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 250

# .find_each is not the same as .each
Rails/FindEach:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Will report offences for many places that are much more readable without using a guard clause
Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/LambdaCall:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/SymbolArray:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/TrivialAccessors:
  ExactNameMatch: true
  Enabled: true
