environment:
  REDIS_URL: redis://redis:6379/0
rvm: true
script:
  - RAILS_ENV=test bundle exec rake db:schema:load
  - xvfb-run bundle exec rspec
  - bundle exec rake best_practice_project:run
services:
  redis:
    image: redis:5.0.7
    expose:
      - 6379
